// <auto-generated />
namespace BrowserTrack.Data.EntityFramework
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterVersionHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterVersionHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201507040332522_AlterVersionHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
