// <auto-generated />
namespace BrowserTrack.Data.EntityFramework
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _16july : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_16july));
        
        string IMigrationMetadata.Id
        {
            get { return "201507161332061_16july"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
